language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: BR4PuGH9WMfbrdnpdH+Ewz1vk0lbZZg7l59OLfq4QlTPCW5HfxwYfnoSuBYS4BwFN1mAP0KhX4AmiS6FXw8rleGf2/8+q/x7mblVMeLqCjebLB406Qwqo+cokRBd7aL3Ce1vSC74qWSrHjPoa8+gDSZgpfCSQqaxRIL2BiOxTOEQbq8uGYUpaJ4abID9sE1vj6yReWzuQUpow7Ahg0KTXSl5PbgBiW/VYsk25PwJf6dMonCi2CSvUKuT6TxBcA8pf+VVPgxk8LA5qm9gDLujaajvVmYa+ZtmsL0jN5d+ktyhT8qv8hNJyGGLYVZ7W+3PGnPscw8Hb8Ge71HY2e4UvQj9JQRZFVEkZi7fbY6Xzm1jHOeDXZV6LVc6twDEnASYbAhYz7KZqRpzA4HaR0BlVxz0p/848Nj5P34tQ6qhqmBxzF+Jrrag781d+b8+fPk/5qAeOdpN6Chi9r6e0LcI6hZW/d2+McBpsTk9gbFszWNu+HgAfNbdgXYW81pUxwPyYl6RbcbcmCdX5I/8IdCNicqtQ85z7oo/Qs5+4TqY5dS9idTkDNqEuyjrUL05UP3CVELhuVBsHUD/mWlc0Y2NJbWB8rG5vuVKF94gM5Wo36UTceEJXcN3+CGgzIjmToFMe3N2cv517JKcJU+8jvVSHjxBBEsc3+vCSnvRaO5aUXI=
  app: intense-river-44339
  on:
    repo: oscaralexander2125/book-keeper-client
