language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: RIdWu52Ts6FNqAGxA348onyL/5o6AUmF7LHuWcnHvg6hEW2OUjxFFIXIRFDZbREmlAgAkLHJGAsxUKLqzQ9qtpKjTF3OvoFRQQo737PJr8PoBZkyeOoco8ExsvFWVh7UKQ3bsXAjzRDcv86IfuVB4hcIjwKQ6+CLsBvIFt7RVcaf5pYf3FiFTqO+9hWaP7aMFgDWSGtV9MXAKYGE07PWyx/qezbEUIqnCBjSnvMsHzVw7ySr9n10M1LKC0lMnANGM0pLNTnFu5h0ikY/XvS/T+ZTvyL1IAQmjkGF6Nts2qfFZBVRfFa0+A14lluTGj85Vo9K30F7LCIy/iZJTqr7LH++Hat88DsLfknh7937T1wP7+c+ZyxmAoVPEy9qEn2wpfPNzeh5xAChdBpZDWLq0+Oobqor0d8bNxegonK1JgWbt49PKYDE4yztAwdZBQ8Brux64KReoX1l5zV+djmmz7JSTlkU6UoVbD2G1LW7N73++ESFAJluuhYaGWGh61eE7NdsQC52ojt+IeziIDY5ER4HLF9fjYkSsstuZOQzqWUpqFRdNvtElx44TowJMSNYt7/WPBGpgPMDUxD+Kv4HWGJ7I299KYTXc+Z0BWnWzl4C2K6DCWdYET0yk1e2Xk5qyRWde+vkbb0dJZS6OEwWirWXCLUeOI9BOKH3nckBO9E=
  app: book-keeper-client
  on:
    repo: oscaralexander2125/book-keeper-client
